language: php

sudo: false

php:
  - 7.2

env:
  - RHOTEST=integration

matrix:
  fast_finish: true

before_script:

before_install:
  - travis_retry composer clear-cache

install:
  - if [[ "$RHOTEST" == "unit" ]]; then travis_retry make dev-env; fi
  - if [[ "$RHOTEST" == "integration" ]]; then travis_retry make no-dev-env; fi
  - travis_retry composer dump-autoload # Dumps autoload-dev too 
  - php -r 'print_r(require("vendor/composer/autoload_psr4.php"));'

script:
  - make "$RHOTEST"-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email: false
